package org.example;// Generated by Selenium IDE

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class AddcontactnameTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "D:\\AQA\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<>();
  }

  public void tearDown() {
    driver.quit();
  }

  public void addcontactname() {
    driver.get("https://crm.geekbrains.space/user/login");
    driver.manage().window().setSize(new Dimension(1272, 792));
    driver.findElement(By.id("prependedInput")).click();
    driver.findElement(By.id("prependedInput")).sendKeys("Applanatest1");
    driver.findElement(By.id("prependedInput2")).click();
    driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
    driver.findElement(By.id("_submit")).click();
   // driver.findElement(By.cssSelector(".first")).click();
    WebElement searchBtn = driver.findElement(By.id("searchbtn"));

    Actions action = new Actions(driver);
    action.moveToElement(searchBtn).perform();

    driver.findElement(By.linkText("Создать контактное лицо")).click();
    driver.findElement(By.id("crm_contact_lastName-uid-612a76f28423c")).sendKeys("Бабук");
    driver.findElement(By.id("crm_contact_firstName-uid-612a76f284177")).click();
    driver.findElement(By.id("crm_contact_firstName-uid-612a76f284177")).sendKeys("Юлия");
    driver.findElement(By.cssSelector(".responsive-section:nth-child(1) .responsive-cell:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("select2-drop-mask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("crm_contact_jobTitle-uid-612a76f28432a")).click();
    driver.findElement(By.id("crm_contact_jobTitle-uid-612a76f28432a")).sendKeys("Boss");
    driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
  }
}
