package org.example;// Generated by Selenium IDE

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class CreateprojectTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "D:\\AQA\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<>();
  }

  public void tearDown() {
    driver.quit();
  }

  public void createproject() {
    driver.get("https://crm.geekbrains.space/user/login");
    driver.manage().window().setSize(new Dimension(1272, 792));
    driver.findElement(By.id("prependedInput")).click();
    driver.findElement(By.id("prependedInput")).sendKeys("Applanatest1");
    driver.findElement(By.id("prependedInput2")).click();
    driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
    driver.findElement(By.id("_submit")).click();
    driver.findElement(By.cssSelector(".dropdown:nth-child(3) .single:nth-child(4) .title")).click();
    driver.findElement(By.linkText("Создать проект")).click();
    driver.findElement(By.id("crm_project_name-uid-612a75474b3b4")).sendKeys("MyBestProject");
    {
      WebElement element = driver.findElement(By.cssSelector(".select2-default > .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("select2-drop-mask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.id("crm_project_businessUnit-uid-612a75476d0a8")).click();
    {
      WebElement dropdown = driver.findElement(By.id("crm_project_businessUnit-uid-612a75476d0a8"));
      dropdown.findElement(By.xpath("//option[. = 'Research & Development']")).click();
    }
    driver.findElement(By.cssSelector("#crm_project_businessUnit-uid-612a75476d0a8 > option:nth-child(2)")).click();
    driver.findElement(By.id("crm_project_curator-uid-612a754798971")).click();
    {
      WebElement dropdown = driver.findElement(By.id("crm_project_curator-uid-612a754798971"));
      dropdown.findElement(By.xpath("//option[. = 'Чернецкий Евгений']")).click();
    }
    driver.findElement(By.cssSelector("#crm_project_curator-uid-612a754798971 > option:nth-child(18)")).click();
    driver.findElement(By.id("crm_project_rp-uid-612a75478fa44")).click();
    {
      WebElement dropdown = driver.findElement(By.id("crm_project_rp-uid-612a75478fa44"));
      dropdown.findElement(By.xpath("//option[. = 'Карпов Руслан55']")).click();
    }
    driver.findElement(By.cssSelector("#crm_project_rp-uid-612a75478fa44 > option:nth-child(19)")).click();
    driver.findElement(By.id("crm_project_manager-uid-612a754779405")).click();
    {
      WebElement dropdown = driver.findElement(By.id("crm_project_manager-uid-612a754779405"));
      dropdown.findElement(By.xpath("//option[. = 'Ломакина Ксения']")).click();
    }
    driver.findElement(By.cssSelector("#crm_project_manager-uid-612a754779405 > option:nth-child(15)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#s2id_crm_project_contactMain-uid-612a75479d1a2 .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#s2id_crm_project_contactMain-uid-612a75479d1a2 .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("select2-drop-mask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
  }
}
